CREATE TABLE ALUMNOS(
	NCONTROL INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    CARRERA VARCHAR(150) NOT NULL,
    ESTATUS VARCHAR(1) NOT NULL
);

CREATE TABLE MAESTROS(
	CLAVEMAESTRO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    DEPARTAMENTO INT NOT NULL,
    ESTATUS VARCHAR(1) NOT NULL
);

CREATE TABLE MATERIAS (
	CLAVEMATERIA VARCHAR(8) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    CREDITOS INT NOT NULL
);

CREATE TABLE GRUPOS(
	CLAVEMATERIA VARCHAR(8) NOT NULL,
    CLAVEGRUPO VARCHAR(4) NOT NULL,
    CLAVEMAESTRO INT NOT NULL,
    LIMITEALUMNOS INT NOT NULL,
    INSCRITOS INT NOT NULL,
    HORARIOLUNES VARCHAR(11),
    HORARIOMARTES VARCHAR(11),
    HORARIOMIERCOLES VARCHAR(11),
    HORARIOJUEVES VARCHAR(11),
    HORARIOVIERNES VARCHAR(11),
    PRIMARY KEY (CLAVEMATERIA, CLAVEGRUPO)
);

ALTER TABLE GRUPOS 
ADD CONSTRAINT FK_GRUPOS_MATERIAS FOREIGN KEY (CLAVEMATERIA) REFERENCES MATERIAS (CLAVEMATERIA),
ADD CONSTRAINT FK_GRUPOS_MAESTROS FOREIGN KEY (CLAVEMAESTRO) REFERENCES MAESTROS (CLAVEMAESTRO);

CREATE TABLE CARGA(
	CLAVEMATERIA VARCHAR(8) NOT NULL,
    CLAVEGRUPO VARCHAR(4) NOT NULL,
    NCONTROL INT NOT NULL
);

ALTER TABLE CARGA
ADD CONSTRAINT FK_CARGA_GRUPO FOREIGN KEY (CLAVEMATERIA, CLAVEGRUPO) REFERENCES GRUPOS (CLAVEMATERIA, CLAVEGRUPO),
ADD CONSTRAINT FK_CARGA_ALUMNOS FOREIGN KEY (NCONTROL) REFERENCES ALUMNOS(NCONTROL);
