version: '3'

services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: 'db'
    environment:
      - MYSQL_DATABASE=minisitec
      - MYSQL_ROOT_PASSWORD=minisitec
    ports:
      - '3306:3307'
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d